Repository jenkinsci/blueocean-plugin, pull requests merged in 2018-02, with the labels that each got.

#1650 JENKINS-47386 fix icon tooltips
  blueocean-dashboard/src/main/js/components/PipelinePage.jsx
  blueocean-dashboard/src/main/js/components/RunDetails.jsx
  blueocean-web/src/main/resources/jenkins/plugins/blueocean/web/Messages.properties
  jenkins-design-language/src/js/components/favorite/Favorite.jsx
Labels: needs-review

#1652 JENKINS-47022 - Fix for dropdown losing focus on selection
  jenkins-design-language/src/js/components/forms/Dropdown.jsx
  jenkins-design-language/test/js/components/Dropdown-spec.jsx
Labels: needs-review

#1654 publish new version of the JDL for JENKINS-47022
  jenkins-design-language/package.json
Labels: ready-for-merge

#1641 JENKINS-47978# Includes fixes related to lightweight PR merge
  pom.xml
Labels: needs-review

#1660 JENKINS-47022 - Fix for dropdown losing focus on selection, back port to 1.4
  jenkins-design-language/package.json
  jenkins-design-language/src/js/components/forms/Dropdown.jsx
  jenkins-design-language/test/js/components/Dropdown-spec.jsx
Labels: needs-review

#1635 JENKINS-48868# Dashboard page load performance fix
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractBlueRunSummary.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStylePipeline.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/TestProject.java
Labels: needs-review

#1638 [FIX JENKINS-44995] favorites can be a cause of slowness and they were broken and using redux
  acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesCardsTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesNavigationTest.java
  blueocean-personalization/.babelrc
  blueocean-personalization/npm-shrinkwrap.json
  blueocean-personalization/package.json
  blueocean-personalization/src/main/js/components/DashboardCards.jsx
  blueocean-personalization/src/main/js/components/FavoritePipeline.jsx
  blueocean-personalization/src/main/js/components/FavoritesProvider.js
  blueocean-personalization/src/main/js/jenkins-js-extension.yaml
  blueocean-personalization/src/main/js/model/FavoriteStore.js
  blueocean-personalization/src/main/js/model/FavoritesSseListener.js
  blueocean-personalization/src/main/js/redux/FavoritesActions.jsx
  blueocean-personalization/src/main/js/redux/FavoritesStore.jsx
  blueocean-personalization/src/test/js/model/FavoritesStore-spec.js
  blueocean-personalization/src/test/js/redux/FavoritesStore-spec.js
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/FavoriteListStatePreloader.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/FavoritesStatePreloader.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FavoriteContainerImpl.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/FavoritesApiTest.java
  blueocean/src/test/java/io/jenkins/blueocean/config/JenkinsJSExtensionsTest.java
Labels: needs-review

#1661 JENKINS-49298 fastsearch steals focus on "t" key
  blueocean-dashboard/src/main/js/components/Pipelines.jsx
  blueocean-dashboard/src/main/less/core.less
Labels: needs-review

#1662 JENKINS-48571# Create MBP SCMSource with Id
  blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractMultiBranchCreateRequest.java
Labels: needs-review

#1667 JENKINS-48820# Fix for stack overflow in flownode sse event generation
  blueocean-events/src/main/java/io/jenkins/blueocean/events/PipelineEventListener.java
  blueocean-events/src/test/java/io/jenkins/blueocean/events/PipelineEventListenerTest.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/FlowNodeWrapper.java
Labels: needs-review

#1666 Hide BlueOceanExportInterceptor so Javadoc can ignore .export package
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/Export.java
Labels: bug, needs-review

#1669 1.4: JENKINS-48868# Dashboard page load performance fix (#1635)
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractBlueRunSummary.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStylePipeline.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/TestProject.java
Labels: enhancement, needs-review

#1671 JENKINS-48074 show full log in case of no steps and no stages for a failed run
  acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
  acceptance-tests/src/test/resources/io/blueocean/ath/offline/multibranch/ParallelNavigationTest/Jenkinsfile.nosteps.nostages
  blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
  jenkins-design-language/less/components/alert.less
Labels: needs-review

#1674 1.4 cherry pick: JENKINS-47395 for github server pipeline creation if url is invalid try appending /api/v3 (#1624)
  acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEnterpriseCreationTest.java
  blueocean-dashboard/src/main/js/creation/github-enterprise/GHEAddServerDialog.jsx
Labels: needs-review

#1678 JENKINS-49756# Fix for BB server defult branch API in bb server >= 5.6.0
  blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerApi.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketApiTest.java
  blueocean-bitbucket-pipeline/src/test/resources/api/server/mappings/mapping-branches-default-5.6.0.json
Labels: needs-review
