Repository jenkinsci/blueocean-plugin, pull requests merged in 2018-04, with the labels that each got.

#1705 JENKINS-50452# Fix node graph visitor log levels
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
Labels: needs-review

#1707 Update to 1.6.0-beta-1-SNAPSHOT for next development cycle
  blueocean-bitbucket-pipeline/pom.xml
  blueocean-commons/pom.xml
  blueocean-config/pom.xml
  blueocean-core-js/pom.xml
  blueocean-dashboard/pom.xml
  blueocean-events/pom.xml
  blueocean-git-pipeline/pom.xml
  blueocean-github-pipeline/pom.xml
  blueocean-i18n/pom.xml
  blueocean-jira/pom.xml
  blueocean-jwt/pom.xml
  blueocean-personalization/pom.xml
  blueocean-pipeline-api-impl/pom.xml
  blueocean-pipeline-editor/pom.xml
  blueocean-pipeline-scm-api/pom.xml
  blueocean-rest-impl/pom.xml
  blueocean-rest/pom.xml
  blueocean-web/pom.xml
  blueocean/pom.xml
  jenkins-design-language/pom.xml
  pom.xml
Labels: needs-review

#1706 Change pom version from beta to 1.5.0-SNAPSHOT for release
  blueocean-bitbucket-pipeline/pom.xml
  blueocean-commons/pom.xml
  blueocean-config/pom.xml
  blueocean-core-js/pom.xml
  blueocean-dashboard/pom.xml
  blueocean-events/pom.xml
  blueocean-git-pipeline/pom.xml
  blueocean-github-pipeline/pom.xml
  blueocean-i18n/pom.xml
  blueocean-jira/pom.xml
  blueocean-jwt/pom.xml
  blueocean-personalization/pom.xml
  blueocean-pipeline-api-impl/pom.xml
  blueocean-pipeline-editor/pom.xml
  blueocean-pipeline-scm-api/pom.xml
  blueocean-rest-impl/pom.xml
  blueocean-rest/pom.xml
  blueocean-web/pom.xml
  blueocean/pom.xml
  jenkins-design-language/pom.xml
  pom.xml
Labels: needs-review

#1698 [JENKINS-50325] Some part of the code uses object.assign which needs to be polyfill to support IE11
  blueocean-core-js/npm-shrinkwrap.json
  blueocean-core-js/package.json
  blueocean-dashboard/npm-shrinkwrap.json
  blueocean-dashboard/package.json
  blueocean-material-icons/package.json
  blueocean-material-icons/src/js/components/SvgIcon/SvgIcon.js
  blueocean-personalization/npm-shrinkwrap.json
  blueocean-personalization/package.json
  blueocean-pipeline-editor/npm-shrinkwrap.json
  blueocean-pipeline-editor/package.json
  blueocean-web/npm-shrinkwrap.json
  blueocean-web/package.json
  jenkins-design-language/npm-shrinkwrap.json
  jenkins-design-language/package.json
  jenkins-design-language/src/js/components/pipeline/PipelineGraph.jsx
Labels: ready-for-merge

#1709 JENKINS-45251 make all text in an input step format according to new lines chars
  blueocean-dashboard/src/main/less/forms/index.less
Labels: needs-review

#1710 JENKINS-49455 & JENKINS-45486 don't step out of karaoke mode when scrolling up if run is paused
  blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
Labels: needs-review

#1708 Task/cleanup url utils
  blueocean-core-js/src/js/ToastUtils.js
  blueocean-core-js/src/js/UrlBuilder.js
  blueocean-core-js/src/js/UrlBuilder.ts
  blueocean-core-js/src/js/index.js
  blueocean-core-js/src/js/parameter/ParametersRunButton.jsx
  blueocean-core-js/src/js/utils/UrlUtils.js
  blueocean-core-js/src/js/utils/UrlUtils.ts
  blueocean-core-js/test/js/UrlBuilder-spec.js
  blueocean-core-js/test/js/UrlUtils-spec.js
  blueocean-core-js/test/js/index-spec.js
  blueocean-dashboard/reports/junit.xml
  blueocean-dashboard/src/main/js/components/Activity.jsx
  blueocean-dashboard/src/main/js/components/ActivityDetailsRow.jsx
  blueocean-dashboard/src/main/js/components/BranchDetailsRow.jsx
  blueocean-dashboard/src/main/js/components/IfCapability.jsx
  blueocean-dashboard/src/main/js/components/PipelinePage.jsx
  blueocean-dashboard/src/main/js/components/PipelineRowItem.jsx
  blueocean-dashboard/src/main/js/components/PipelineTrends.jsx
  blueocean-dashboard/src/main/js/components/PullRequestRow.jsx
  blueocean-dashboard/src/main/js/components/RunDetails.jsx
  blueocean-dashboard/src/main/js/components/RunDetailsArtifacts.jsx
  blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
  blueocean-dashboard/src/main/js/components/RunHistoryButton.jsx
  blueocean-dashboard/src/main/js/components/downstream-runs/DownstreamRunsView.jsx
  blueocean-dashboard/src/main/js/components/karaoke/components/LogToolbar.jsx
  blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
  blueocean-dashboard/src/main/js/components/karaoke/rest/KaraokeApi.js
  blueocean-dashboard/src/main/js/components/karaoke/urls/detailUrl.js
  blueocean-dashboard/src/main/js/creation/ClassicCreationLink.jsx
  blueocean-dashboard/src/main/js/creation/bitbucket/steps/BbCompleteStep.jsx
  blueocean-dashboard/src/main/js/creation/git/GitCompletedStep.jsx
  blueocean-dashboard/src/main/js/util/UrlUtils.js
  blueocean-dashboard/src/test/js/UrlUtils-spec.js
  blueocean-personalization/src/main/js/components/PipelineCard.jsx
  blueocean-pipeline-editor/src/main/js/EditorPage.jsx
  blueocean-pipeline-editor/src/main/js/api/ScmContentApi.js
  blueocean-web/src/main/js/main.jsx
Labels: enhancement, needs-review

#1722 JENKINS-48075 add next/prev links to run details screen
  blueocean-dashboard/src/main/js/components/RunDetailsHeader.jsx
  blueocean-dashboard/src/main/less/run-details-header.less
  blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
  blueocean-dashboard/src/test/js/run-details-id-navigation-spec.js
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/AbstractRunImplTest.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractRunImpl.java
  jenkins-design-language/less/components/material-icon.less
Labels: needs-review

#1720 Git https auth round trip
  acceptance-tests/package-lock.json
  acceptance-tests/run.sh
  acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/GitCreationPage.java
  acceptance-tests/src/test/java/io/blueocean/ath/live/creation/GitCreationTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/BitbucketServerTest.java
  blueocean-core-js/gulpfile.js
  blueocean-core-js/npm-shrinkwrap.json
  blueocean-core-js/package.json
  blueocean-core-js/src/js/UrlBuilder.ts
  blueocean-core-js/src/js/bundleStartup.js
  blueocean-core-js/src/js/components/LiveStatusIndicator.jsx
  blueocean-core-js/src/js/paths/index.js
  blueocean-core-js/test/js/User-spec.js
  blueocean-core-js/test/js/components/ReplayButton-spec.js
  blueocean-core-js/test/js/components/RunButton-spec.js
  blueocean-core-js/test/js/components/TimeHarmonizer-spec.js
  blueocean-core-js/test/js/fetch-spec.js
  blueocean-core-js/test/js/urlconfig-spec.js
  blueocean-dashboard/npm-shrinkwrap.json
  blueocean-dashboard/package.json
  blueocean-dashboard/src/main/js/creation/credentials/CreateCredentialDialog.jsx
  blueocean-dashboard/src/main/js/creation/credentials/index.js
  blueocean-dashboard/src/main/js/creation/git/GitConnectStep.jsx
  blueocean-dashboard/src/main/js/credentials/CredentialsPicker.jsx
  blueocean-dashboard/src/main/js/credentials/TypedError.js
  blueocean-dashboard/src/main/js/credentials/TypedError.ts
  blueocean-dashboard/src/main/js/credentials/bitbucket/BbCredentialsApi.js
  blueocean-dashboard/src/main/js/credentials/bitbucket/BbCredentialsManager.js
  blueocean-dashboard/src/main/js/credentials/bitbucket/BbCredentialsPicker.jsx
  blueocean-dashboard/src/main/js/credentials/bitbucket/BbCredentialsState.js
  blueocean-dashboard/src/main/js/credentials/git/GitCredentialsPicker.jsx
  blueocean-dashboard/src/main/js/credentials/git/GitCredentialsPickerPassword.tsx
  blueocean-dashboard/src/main/js/credentials/git/GitCredentialsPickerSSH.jsx
  blueocean-dashboard/src/main/js/credentials/git/GitPWCredentialsApi.ts
  blueocean-dashboard/src/main/js/credentials/git/GitPWCredentialsManager.ts
  blueocean-dashboard/src/main/js/credentials/github/GithubCredentialsApi.js
  blueocean-dashboard/src/main/less/creation/git.less
  blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
  blueocean-dashboard/src/test/js/creation/git/GitPWCredentialsManager-spec.js
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveRequest.java
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveService.java
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScm.java
  blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScmTest.java
  blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScmTest2.java
  blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitUtilsTest.java
  blueocean-pipeline-editor/npm-shrinkwrap.json
  blueocean-pipeline-editor/package.json
  blueocean-pipeline-editor/src/main/js/EditorPage.jsx
  blueocean-pipeline-editor/src/main/js/api/ScmContentApi.js
  blueocean-pipeline-editor/src/main/js/api/TypedError.js
  blueocean-web/npm-shrinkwrap.json
  blueocean-web/package.json
  jenkins-design-language/npm-shrinkwrap.json
  jenkins-design-language/package.json
  js-extensions/@jenkins-cd/js-builder.js
  js-extensions/src/init/blueocean-core-js.js
Labels: enhancement, needs-review
