Repository jenkinsci/blueocean-plugin, pull requests merged in 2018-10, with the labels that each got.

#1812 Remove unused zombie dependency
  blueocean-web/npm-shrinkwrap.json
  blueocean-web/package.json
Labels: needs-review

#1823 Update jelly escaping defaults - master (#1820)
  blueocean-config/src/main/resources/io/jenkins/blueocean/config/RollbarDecorator/header.jelly
  blueocean-web/src/main/resources/io/jenkins/blueocean/PageStatePreloadDecorator/header.jelly
Labels: ready-for-merge

#1832 [JENKINS-46730] Add support for multiple pages when getting orgs (projects) from bitbucket
  blueocean-dashboard/src/main/js/creation/bitbucket/api/BbCreationApi.js
Labels: needs-review

#1836 JENKINS-53900 Missing stage graph nodes
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
Labels: bug, needs-review
