Repository jenkinsci/blueocean-plugin, pull requests merged in 2018-03, with the labels that each got.

#1679 Add prettier.js setup instructions to README
  README.md
Labels: enhancement, needs-review

#1675 Downstream job links UI
  acceptance-tests/src/test/java/io/blueocean/ath/offline/pipeline/DownstreamLinkTest.java
  blueocean-dashboard/src/main/js/components/PipelinePage.jsx
  blueocean-dashboard/src/main/js/components/RunDetails.jsx
  blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
  blueocean-dashboard/src/main/js/components/downstream-runs/DownstreamRuns.jsx
  blueocean-dashboard/src/main/js/components/downstream-runs/DownstreamRunsView.jsx
  blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
  blueocean-dashboard/src/main/js/components/karaoke/services/Augmenter.js
  blueocean-dashboard/src/main/js/components/stories/DownstreamRunsStories.js
  blueocean-dashboard/src/main/js/components/stories/index.js
  blueocean-dashboard/src/main/js/util/logDisplayHelper.js
  blueocean-dashboard/src/main/less/run-details-header.less
  blueocean-dashboard/src/main/less/tables.less
  blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
  blueocean-dashboard/src/test/js/components/DownstreamRuns-spec.js
  jenkins-design-language/src/js/components/jtable/JTable.jsx
Labels: enhancement, needs-review

#1676 JENKINS-45334 go to classic link missing in invalid input param
  acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
  acceptance-tests/src/test/resources/io/blueocean/ath/offline/multibranch/ParallelNavigationTest/Jenkinsfile.input.param.classic.link
  blueocean-core-js/src/js/utils/UrlUtils.js
  blueocean-dashboard/src/main/js/components/karaoke/components/InputStep.jsx
  blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
  blueocean-dashboard/src/main/js/components/karaoke/components/Step.jsx
Labels: needs-review

#1683 remove duplicate code introduced in fix for JENKINS-45334
  blueocean-dashboard/src/main/js/components/karaoke/components/InputStep.jsx
Labels: needs-review

#1684 [JENKINS-48274] Set default email for git commit
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitBareRepoReadSaveRequest.java
  blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveTest.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
Labels: needs-review

#1686 JENKINS-49929 Regression: Log fails to auto update in karaoke mode
  blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
  blueocean-dashboard/src/main/js/components/karaoke/components/Step.jsx
Labels: bug, needs-review

#1689 [JENKINS-48027] Properly encode branch names
  acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/NavigationTest.java
  blueocean-core-js/src/js/paths/rest.js
  blueocean-core-js/src/js/utils/jenkins-encode.js
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
Labels: needs-review

#1690 [JENKINS-43892] Show passing tests
  acceptance-tests/src/main/java/io/blueocean/ath/AthModule.java
  acceptance-tests/src/main/java/io/blueocean/ath/GitRepositoryRule.java
  acceptance-tests/src/main/java/io/blueocean/ath/factory/RunDetailsTestsPageFactory.java
  acceptance-tests/src/main/java/io/blueocean/ath/model/AbstractPipeline.java
  acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/RunDetailsTestsPage.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/TestDetailsTest.java
  acceptance-tests/src/test/resources/io/blueocean/ath/offline/edgeCases/TestDetailsTest/Jenkinsfile
  acceptance-tests/src/test/resources/io/blueocean/ath/offline/edgeCases/TestDetailsTest/TEST-failure.TestThisWillFailAbunch.xml
  acceptance-tests/src/test/resources/io/blueocean/ath/offline/edgeCases/TestDetailsTest/TEST-failure.TestThisWontFail.xml
  blueocean-dashboard/src/main/js/components/testing/TestResults.jsx
  blueocean-dashboard/src/main/js/components/testing/TestService.js
  blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
  blueocean-dashboard/src/test/js/testResult-spec.js
Labels: needs-review

#1687 [FIX-JENKINS-49702] JTable produces a console warning
  jenkins-design-language/src/js/components/jtable/JTable.jsx
Labels: needs-review

#1685 JENKINS-45634 Table action buttons hidden until hover
  acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesCardsTest.java
  blueocean-dashboard/src/main/js/components/BranchDetailsRow.jsx
  blueocean-dashboard/src/main/js/components/PullRequestRow.jsx
  blueocean-personalization/src/main/js/components/PipelineCard.jsx
  blueocean-personalization/src/main/less/pipeline-card.less
  jenkins-design-language/less/components/jtable.less
  jenkins-design-language/less/theme.less
Labels: needs-review

#1688 [FIX-JENKINS-49948] vulnerabilities in bo js dependencies
  blueocean-core-js/npm-shrinkwrap.json
  blueocean-core-js/package.json
  blueocean-core-js/src/js/utils/TimeManager.js
  blueocean-dashboard/npm-shrinkwrap.json
  blueocean-dashboard/package.json
  blueocean-personalization/npm-shrinkwrap.json
  blueocean-personalization/package.json
  blueocean-pipeline-editor/npm-shrinkwrap.json
  blueocean-pipeline-editor/package.json
  blueocean-web/npm-shrinkwrap.json
  blueocean-web/package.json
  jenkins-design-language/npm-shrinkwrap.json
  jenkins-design-language/package.json
  jenkins-design-language/test/js/components/TimeDuration-spec.jsx
Labels: needs-review

#1692 Typescript support
  acceptance-tests/package-lock.json
  acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
  bin/rebuildShrinkwrap.js
  blueocean-config/npm-shrinkwrap.json
  blueocean-config/package.json
  blueocean-core-js/gulpfile.js
  blueocean-core-js/npm-shrinkwrap.json
  blueocean-core-js/package.json
  blueocean-core-js/src/js/fetch.ts
  blueocean-core-js/tsconfig.json
  blueocean-dashboard/npm-shrinkwrap.json
  blueocean-dashboard/package.json
  blueocean-dashboard/src/main/js/Dashboard.jsx
  blueocean-dashboard/src/main/js/Dashboard.tsx
  blueocean-dashboard/src/main/js/components/testing/TestResults.tsx
  blueocean-dashboard/src/test/js/testResult-spec.js
  blueocean-dashboard/src/test/js/util/EnzymeUtils.js
  blueocean-dashboard/tsconfig.json
  blueocean-personalization/npm-shrinkwrap.json
  blueocean-personalization/package.json
  blueocean-pipeline-editor/npm-shrinkwrap.json
  blueocean-pipeline-editor/package.json
  blueocean-pipeline-editor/src/main/js/components/Accordion.tsx
  blueocean-pipeline-editor/tsconfig.json
  blueocean-web/npm-shrinkwrap.json
  blueocean-web/package.json
  blueocean-web/src/main/java/io/jenkins/blueocean/dev/RunBundleWatches.java
  blueocean-web/src/main/js/config.ts
  blueocean-web/tsconfig.json
  jenkins-design-language/gulpfile.js
  jenkins-design-language/npm-shrinkwrap.json
  jenkins-design-language/package.json
  jenkins-design-language/src/js/Utils.ts
  jenkins-design-language/tsconfig.json
  js-extensions/package.json
  tsconfig.json
Labels: needs-review

#1699 JENKINS-50406 "Triggered Build" links broken with cloudbees-folder
  blueocean-core-js/src/js/UrlBuilder.js
  blueocean-core-js/src/js/utils/UrlUtils.js
  blueocean-dashboard/src/main/js/components/downstream-runs/DownstreamRunsView.jsx
  blueocean-dashboard/src/main/js/util/UrlUtils.js
Labels: bug, needs-review

#1702 JENKINS-48884 Fix parallel stages not rendering properly if skipped by failed previous stage
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeUtil.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepVisitor.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
  blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/parallelStepsFromPost.jenkinsfile
Labels: needs-review

#1704 JENKINS-48357# Fix jira-plugin binary compatibility issue
  blueocean/pom.xml
  pom.xml
Labels: needs-review
