Repository jenkinsci/blueocean-plugin, pull requests merged in 2019-10, with the labels that each got.

#2028 Hacktoberfest - Project URL updated to use Github instead of Wiki
  pom.xml
Labels: enhancement, hacktoberfest

#2027 JENKINS-39225: add i18n Korean support
  blueocean-dashboard/src/main/js/TopPipelinesLink.jsx
  blueocean-dashboard/src/main/js/creation/git/steps/LoadingStep.jsx
  blueocean-dashboard/src/main/js/creation/github/steps/GithubCredentialStep.jsx
  blueocean-dashboard/src/main/js/creation/github/steps/GithubLoadingStep.jsx
  blueocean-dashboard/src/main/js/creation/github/steps/GithubOrgListStep.jsx
  blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages_ko.properties
  blueocean-personalization/src/main/resources/jenkins/plugins/blueocean/personalization/Messages_ko.properties
  blueocean-pipeline-editor/src/main/resources/jenkins/plugins/blueocean/pipeline/editor/Messages_ko.properties
  blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_ko.properties
  blueocean-web/src/main/js/main.jsx
  blueocean-web/src/main/resources/jenkins/plugins/blueocean/web/Messages_ko.properties
Labels: enhancement

#2026 Ensure header is visible on scroll
  jenkins-design-language/less/components/result-status.less
Labels: bug
