Repository jenkinsci/blueocean-plugin, pull requests merged in 2019-02, with the labels that each got.

#1910 Update SSE client lib used in ATH
  acceptance-tests/src/main/java/io/blueocean/ath/sse/SSEClientRule.java
Labels: enhancement, needs-review

#1912 [JENKINS-55986] Don't show the "Restart Stage" link if permissions do not allow it
  blueocean-dashboard/src/main/js/components/StageRestartLink.tsx
  blueocean-dashboard/src/test/js/data/pipelines/pipelinesSingle.js
  blueocean-dashboard/src/test/js/stageRestart-spec.js
Labels: needs-review

#1918 Fix for declarative pipelines sometimes dropping downstream build links
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/FlowNodeWrapper.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
  blueocean-pipeline-api-impl/src/main/java/org/jenkinsci/plugins/workflow/job/views/GraphDumpAction.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
  blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/downstreamBuildLinksDecl.jenkinsfile
  blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/downstreamBuildLinksSeq.jenkinsfile
Labels: bug, needs-review

#1916 [JENKINS-53022] Add endpoint and capability to determine if enable/disable
  blueocean-core-js/npm-shrinkwrap.json
  blueocean-core-js/package.json
  blueocean-core-js/src/js/bundleStartup.js
  blueocean-core-js/src/js/components/DisablePipelineButton.jsx
  blueocean-core-js/src/js/index.ts
  blueocean-core-js/src/js/rest/DisableJobApi.js
  blueocean-core-js/src/less/variables.less
  blueocean-dashboard/npm-shrinkwrap.json
  blueocean-dashboard/package.json
  blueocean-dashboard/src/main/js/components/Activity.jsx
  blueocean-dashboard/src/main/less/core.less
  blueocean-dashboard/src/main/resources/jenkins/plugins/blueocean/dashboard/Messages.properties
  blueocean-dashboard/src/test/js/activity-spec.js
  blueocean-dashboard/src/test/js/data/pipelines/pipelinesSingle.js
  blueocean-material-icons/package-lock.json
  blueocean-material-icons/package.json
  blueocean-material-icons/src/js/components/index.js
  blueocean-material-icons/src/js/components/svg-icons/action/check-circle-outline.js
  blueocean-personalization/npm-shrinkwrap.json
  blueocean-personalization/package.json
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderPipelineImpl.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderTest.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderTest2.java
  blueocean-pipeline-editor/npm-shrinkwrap.json
  blueocean-pipeline-editor/package.json
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStylePipeline.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/util/Disabler.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImplTest.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImplTest.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/util/DisablerTest.java
  blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipeline.java
  blueocean-web/npm-shrinkwrap.json
  blueocean-web/package.json
  jenkins-design-language/npm-shrinkwrap.json
  jenkins-design-language/package.json
Labels: needs-review

#1921 [JENKINS-56301] add missing referrer and robots meta tags
  blueocean-web/src/main/resources/io/jenkins/blueocean/BlueOceanUI/index.jelly
Labels: needs-review

#1917 JENKINS-53019 - Changes tab does not group changes for multiple SCM providers by SCM
  blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
  blueocean-dashboard/src/main/less/core.less
  blueocean-dashboard/src/test/js/data/runs/latestRuns.js
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImpl.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineRunImplTest.java
  blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/mulitpleScms.jenkinsfile
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetResource.java
  blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BlueChangeSetEntry.java
Labels: enhancement, needs-review
