Repository jenkinsci/blueocean-plugin, pull requests merged in 2020-10, with the labels that each got.

#2108 Update parent & use recommended jenkins-test-harness
  pom.xml
Labels: maintenance

#2111 Remove unused jquery-detached js dependency
  blueocean-web/package-lock.json
  blueocean-web/package.json
Labels: chore

#2114 [JENKINS-63979] tombstone blueocean executor info plugin
  acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
  acceptance-tests/src/test/java/io/blueocean/ath/offline/dashboard/DashboardTest.java
  blueocean-executor-info/pom.xml
  blueocean-executor-info/src/main/java/io/jenkins/blueocean/executor/Computers.java
  blueocean-executor-info/src/main/java/io/jenkins/blueocean/executor/ExecutorinfoPreloader.java
  blueocean-executor-info/src/main/js/ExecutorInfoPage.jsx
  blueocean-executor-info/src/main/js/ExecutorInfoService.js
  blueocean-executor-info/src/main/js/ItemExecutorInfo.jsx
  blueocean-executor-info/src/main/js/Routes.jsx
  blueocean-executor-info/src/main/js/TopLink.jsx
  blueocean-executor-info/src/main/js/jenkins-js-extension.yaml
  blueocean-executor-info/src/main/less/extensions.less
  blueocean-executor-info/src/main/resources/index.jelly
  blueocean/pom.xml
Labels: removed

#2109 Remove non needed anymore inner class (SECURITY-380)
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
Labels: chore

#2107 reduce network usages
  blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
Labels: enhancement

#2117 Make executor plugin optional
  blueocean/pom.xml
Labels: removed
