Repository jenkinsci/blueocean-plugin, pull requests merged in 2021-11, with the labels that each got.

#2214 minor improvment/warning fixes
  blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/HttpResponse.java
  blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerEndpoint.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketApiTest.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketCloudScmContentProviderTest.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerScmContentProviderTest.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/Export.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/TreeResponse.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ClassAttributeBehaviour.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/DataWriter.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ExportInterceptor.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/JSONDataWriter.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/MethodProperty.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ModelBuilder.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/NotExportableException.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/TreePruner.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/TypeUtil.java
  blueocean-commons/src/test/java/io/jenkins/blueocean/commons/stapler/export/ModelTest.java
  blueocean-config/src/test/java/io/jenkins/blueocean/config/BlueOceanConfigFactoryTest.java
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/CloneProgressMonitor.java
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitBareRepoReadSaveRequest.java
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitUtils.java
  blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
  blueocean-i18n/src/main/java/io/jenkins/blueocean/i18n/BlueI18n.java
  blueocean-jira/src/main/java/io/jenkins/blueocean/service/embedded/jira/BlueJiraIssue.java
  blueocean-jira/src/main/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListener.java
  blueocean-jira/src/test/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListenerTest.java
  blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/JwtAuthenticationStore.java
  blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/JwtAuthenticationStoreFactory.java
  blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/JwtTokenVerifier.java
  blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/impl/JwtAuthenticationFilter.java
  blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/impl/JwtAuthenticationServiceImpl.java
  blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/impl/JwtTokenVerifierImpl.java
  blueocean-jwt/src/main/java/io/jenkins/blueocean/auth/jwt/impl/SimpleJwtAuthenticationStore.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/BlueUrlTokenizer.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchContainerImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/BranchImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/InputStepImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchPipelineContainerImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineJobFilters.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeGraphVisitor.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineStepImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PrimaryBranch.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/ScmResourceImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/scm/ScmContentProviderParams.java
  blueocean-pipeline-editor/src/main/java/io/blueocean/rest/pipeline/editor/ExportedPipelineStep.java
  blueocean-pipeline-editor/src/main/java/io/blueocean/rest/pipeline/editor/ExportedToolDescriptor.java
  blueocean-pipeline-editor/src/main/java/io/blueocean/rest/pipeline/editor/PipelineMetadataService.java
  blueocean-pipeline-editor/src/test/java/io/blueocean/rest/pipeline/editor/PipelineMetadataServiceTest.java
  blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/credential/BlueOceanCredentialsProvider.java
  blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/scm/api/AbstractPipelineCreateRequest.java
  blueocean-pipeline-scm-api/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/credential/BlueOceanCredentialsProviderTest.java
  blueocean-rest/src/main/java/io/jenkins/blueocean/rest/factory/BlueTestResultFactory.java
Labels: maintenance

#2218 adapt to master terminology change
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
Labels: bug

#2216 Replace OsUtils.isUnix with Functions.isWindows
  blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveTest.java
Labels: chore, maintenance

#2215 Update BOM
  pom.xml
Labels: chore, maintenance
