Repository jenkinsci/blueocean-plugin, pull requests merged in 2021-03, with the labels that each got.

#2132 [JENKINS-58732] Remove docker-workflow dep from blueocean-pipeline-editor
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
  blueocean-pipeline-editor/pom.xml
  blueocean-pipeline-editor/src/test/java/io/blueocean/rest/pipeline/editor/PipelineMetadataServiceTest.java
  blueocean-rest-impl/pom.xml
  blueocean/pom.xml
  pom.xml
Labels: chore, maintenance

#2134 Bump parent version 4.16, bom version 25
  pom.xml
Labels: dependencies, java

#2135 use slf4j, commons-io, commons-lang, commons-codec version coming from bom and mark them as provided
  Jenkinsfile
  acceptance-tests/pom.xml
  acceptance-tests/runner/runtime/pom.xml
  blueocean-git-pipeline/pom.xml
  blueocean-pipeline-scm-api/pom.xml
  pom.xml
Labels: dependencies, java

#2139 Upgrade ath test to use jenkins core 2.222.4 same as one defined in plugin pom
  Jenkinsfile
  acceptance-tests/runner/runtime-plugins/fake-security-realm-plugin/pom.xml
  acceptance-tests/runner/runtime-plugins/runtime-deps/pom.xml
  acceptance-tests/runner/scripts/args.sh
  acceptance-tests/src/main/java/io/blueocean/ath/ATHJUnitRunner.java
  acceptance-tests/src/main/java/io/blueocean/ath/AthModule.java
  acceptance-tests/src/main/java/io/blueocean/ath/CustomJenkinsServer.java
  acceptance-tests/src/main/java/io/blueocean/ath/GitRepositoryRule.java
  acceptance-tests/src/main/java/io/blueocean/ath/LogEntryLogger.java
  acceptance-tests/src/main/java/io/blueocean/ath/SmartWebElement.java
  acceptance-tests/src/main/java/io/blueocean/ath/WaitUtil.java
  acceptance-tests/src/main/java/io/blueocean/ath/api/classic/ClassicJobApi.java
  acceptance-tests/src/main/java/io/blueocean/ath/model/MultiBranchPipeline.java
  acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/ActivityPage.java
  acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/BranchPage.java
  acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/DashboardPage.java
  acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/FavoritesDashboardPage.java
  acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/RunDetailsPipelinePage.java
  acceptance-tests/src/main/java/io/blueocean/ath/sse/SSEClientRule.java
  acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/FolderTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/CommitMessagesTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/AbstractFavoritesTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesAddRemoveTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesCardsTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesNavigationTest.java
  acceptance-tests/src/test/resources/io/blueocean/ath/offline/multibranch/ParallelNavigationTest/Jenkinsfile.failed.input
  blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequest.java
  blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
  blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmContentProvider.java
  blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubServerContainer.java
  blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/HttpRequest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubIssueTest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmTest.java
  blueocean-pipeline-scm-api/src/main/java/io/jenkins/blueocean/credential/CredentialsUtils.java
  pom.xml
Labels: chore, dependencies, maintenance, test
