Repository jenkinsci/blueocean-plugin, pull requests merged in 2021-05, with the labels that each got.

#2009 Show "Run build steps in a container" from Kubernetes plugin
  blueocean-pipeline-editor/src/main/java/io/blueocean/rest/pipeline/editor/PipelineMetadataService.java
Labels: enhancement, needs-review

#2060 Increase height of result item label desc in logConsole
  blueocean-dashboard/src/main/less/core.less
Labels: enhancement

#2166 [JENKINS-65593] Fix test error for Jenkins >= 2.281
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeTest.java
Labels: chore, java, maintenance

#2168 Added support for favorites for primary branches names other than "master"
  acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesNavigationTest.java
  blueocean-personalization/src/main/js/components/FavoritePipeline.jsx
  blueocean-personalization/src/main/js/model/FavoriteStore.js
  blueocean-personalization/src/main/js/model/FavoritesSseListener.js
  blueocean-personalization/src/main/js/util/FavoriteUtils.js
  blueocean-personalization/src/test/js/model/FavoritesStore-spec.js
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/FavoriteListStatePreloader.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/preload/FavoriteListStatePreloaderTest.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineBaseTest.java
Labels: enhancement

#2169 Remove JSR-305 annotations from Blue-Ocean and replaced it with Spotbugs.
  blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/AbstractBitbucketScmContentProvider.java
  blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/HttpRequest.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/PageStatePreloader.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/Export.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/DataWriter.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/JSONDataWriter.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/Model.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/ModelBuilder.java
  blueocean-commons/src/main/java/io/jenkins/blueocean/commons/stapler/export/XMLDataWriter.java
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScm.java
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/ssh/UserSSHKeyManager.java
  blueocean-i18n/src/main/java/io/jenkins/blueocean/i18n/BlueI18n.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/PipelineBranchRunStatePreloader.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/preload/PipelineStatePreloader.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanRootAction.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/JwtTokenServiceEndpointImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/AbstractPipelineImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ArtifactContainerImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ArtifactImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BlueTestResultContainerImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/BlueTrendContainerImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ChangeSetResource.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/ContainerFilter.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/FreeStyleRunImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogAppender.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/LogResource.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/OrganizationImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineContainerImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/PipelineFolderImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueContainerImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueueUtil.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/QueuedBlueRun.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/RunContainerImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserContainerImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/rest/UserImpl.java
Labels: chore, maintenance
