Repository jenkinsci/blueocean-plugin, pull requests merged in 2022-08, with the labels that each got.

#2317 Removing `instance-identity` dependency
  blueocean-pipeline-api-impl/pom.xml
  blueocean-rest-impl/pom.xml
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/analytics/AbstractAnalytics.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/AnalyticsTest.java
  pom.xml
Labels: removed

#2325 Adding Blue Ocean statement
  README.md
  blueocean/doc/BlueOcean.adoc
Labels: documentation

#2305 Fix missing parentheses causing logic bug for tests tab failure count
  blueocean-dashboard/src/main/js/components/RunDetailsTests.jsx
Labels: bug

#2330 [JENKINS-47929] revert
  .prettierrc.yaml
  blueocean-core-js/src/js/index.ts
  blueocean-core-js/src/js/utils/ComponentLink.js
  blueocean-dashboard/src/main/js/PipelineRoutes.jsx
  blueocean-dashboard/src/main/js/components/RunDetails.jsx
  blueocean-dashboard/src/main/js/components/RunDetailsArtifacts.jsx
  blueocean-dashboard/src/main/js/components/RunDetailsChanges.jsx
  blueocean-dashboard/src/main/js/components/RunDetailsTests.jsx
  blueocean-dashboard/src/main/js/components/index.jsx
  blueocean-dashboard/src/main/js/jenkins-js-extension.yaml
  blueocean-dashboard/src/test/js/run-details-changes-spec.js
Labels: bug

#2328 Remove powermock usage
  blueocean-bitbucket-pipeline/pom.xml
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/BitbucketWireMockBase.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/HttpResponseTest.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketApiTest.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketCloudScmContentProviderTest.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketApiTest.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerEndpointTest.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerEndpointWrongVersionTest.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketServerScmContentProviderTest.java
  blueocean-bitbucket-pipeline/src/test/resources/api/server_wrong_version/__files/body-1.0-application-properties-q4jwO.json
  blueocean-bitbucket-pipeline/src/test/resources/api/server_wrong_version/__files/body-1.0-projects-rP9po.json
  blueocean-bitbucket-pipeline/src/test/resources/api/server_wrong_version/mappings/bitbucket_rest_api_10_projects_testp_repos_pipeline-demo-test_browse_somefile-7269cd83-1af6-4134-9161-82360d678dcc.json
  blueocean-bitbucket-pipeline/src/test/resources/api/server_wrong_version/mappings/mapping-1.0-application-properties-q4jwO.json
  blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitScmTest.java
  blueocean-github-pipeline/pom.xml
  blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubApiTest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubEnterpriseApiTest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubEnterpriseScmContentProviderTest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubIssueTest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubMockBase.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubOrgFolderPermissionsTest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmContentProviderTest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScmTest.java
  blueocean-jira/src/test/java/io/jenkins/blueocean/service/embedded/jira/BlueJiraIssueTest.java
  blueocean-jira/src/test/java/io/jenkins/blueocean/service/embedded/jira/JiraSCMListenerTest.java
  blueocean-pipeline-api-impl/pom.xml
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/BranchMetadataTest.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/CachesTest.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/OrganizationFolderTest.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineJobFiltersTest.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImplTest.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeUtilTest.java
  blueocean-pipeline-scm-api/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/credential/BlueOceanCredentialsProviderTest.java
  blueocean-rest-impl/pom.xml
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/ContainerFilterTest.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/BrowserAndOperatingSystemAnalyticsPropertiesTest.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/ArtifactImplTest.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/FreeStylePipelineTest.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/UserImplPermissionTest.java
  pom.xml
Labels: maintenance
