Repository jenkinsci/blueocean-plugin, pull requests merged in 2022-05, with the labels that each got.

#2254 [JENKINS-41488] Better handling of scrolling
  blueocean-dashboard/src/main/js/components/RunDetailsPipeline.jsx
Labels: enhancement

#2283 use already built image
  Jenkinsfile
Labels: maintenance

#2275 [JENKINS-68065] fix Bitbucket cloud job creation via wizard
  blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/cloud/BitbucketCloudApi.java
  blueocean-bitbucket-pipeline/src/test/resources/api/cloud/mappings/mapping-2.0-teams-49APQ.json
Labels: bug

#2282 Make a comment more inclusive
  blueocean-core-js/README.md
Labels: maintenance

#2278 Make a comment more inclusive
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/OrganizationFactoryImpl.java
Labels: maintenance
