Repository jenkinsci/blueocean-plugin, pull requests merged in 2023-08, with the labels that each got.

#2470 Tolerate testing in PCT context
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/rest/BlueTrendTest.java
Labels: test

#2473 upgrade core to 2.401.3 in other places as documented in the pom :)
  Jenkinsfile
  acceptance-tests/runner/scripts/args.sh
Labels: skip-changelog

#2474 Revert "Allow the user to tell the difference between a helpful open button and a generic one (#2442)"
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/BlueOceanUrlObjectImpl.java
  blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages.properties
  blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_ko.properties
  blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_ru.properties
  blueocean-rest-impl/src/main/resources/io/jenkins/blueocean/service/embedded/Messages_zh_CN.properties
Labels: bug

#2472 Remove snake yaml dependency
  blueocean-rest-impl/pom.xml
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/analytics/BrowserAndOperatingSystemAnalyticsProperties.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/BrowserAndOperatingSystemAnalyticsPropertiesTest.java
  pom.xml
Labels: removed

#2479 Merge 1.27.5.x with SECURITY-3116 fix into default branch
  blueocean-github-pipeline/src/main/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubScm.java
  blueocean-pipeline-editor/src/main/js/EditorPage.jsx
  pom.xml
Labels: no-changelog

#2478 remove obsolete config
  pom.xml
Labels: maintenance

#2471 Upgrade some dependencies
  blueocean-git-pipeline/pom.xml
  blueocean-rest-impl/pom.xml
  pom.xml
Labels: dependencies

#2480 Update plugin BOM
  blueocean-rest-impl/pom.xml
  pom.xml
Labels: developer

#2482 Update plugin POM
  pom.xml
Labels: dependencies, java

#2483 no need to declare javadoc plugin just inherit that
  pom.xml
Labels: no-changelog

#2485 [JENKINS-71803] Blue Ocean tests fail on Java 21 with Mockito errors
  blueocean-bitbucket-pipeline/pom.xml
  blueocean-github-pipeline/pom.xml
  blueocean-rest-impl/pom.xml
  pom.xml
Labels: developer

#2488 Use JaCoCo version from plugin parent POM
  blueocean-commons/pom.xml
  pom.xml
Labels: developer
