Repository jenkinsci/blueocean-plugin, pull requests merged in 2023-05, with the labels that each got.

#2433 Use `io.jenkins.plugins:commons-lang3-api`
  blueocean-commons/pom.xml
  blueocean-pipeline-editor/pom.xml
  pom.xml
Labels: dependencies

#2435 Bump BOM and explicitly depend on `caffeine-api` to fix `LoadingCache.refresh`
  blueocean-events/pom.xml
  blueocean-git-pipeline/pom.xml
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/CloneProgressMonitor.java
  blueocean-git-pipeline/src/test/java/io/jenkins/blueocean/blueocean_git_pipeline/GitReadSaveTest.java
  blueocean-pipeline-api-impl/pom.xml
  blueocean-rest-impl/pom.xml
  pom.xml
Labels: dependencies

#2332 [JENKINS-54250] Disable restarting stages in Jenkinsfile optionally
  blueocean-pipeline-api-impl/pom.xml
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImplTest.java
  blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/JENKINS-54250-restartFromStageDisabled.jenkinsfile
  blueocean-pipeline-api-impl/src/test/resources/io/jenkins/blueocean/rest/impl/pipeline/JENKINS-54250-restartFromStageEnabled.jenkinsfile
Labels: enhancement

#2438 Fix typo in description
  blueocean-jira/src/main/resources/index.jelly
Labels: documentation
