Repository jenkinsci/blueocean-plugin, pull requests merged in 2023-09, with the labels that each got.

#2491 Miscellaneous dependency cleanup
  blueocean-pipeline-api-impl/pom.xml
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/RestartStageTest.java
  blueocean-rest-impl/pom.xml
  pom.xml
Labels: skip-changelog

#2495 Fix some failing ATH tests, increase some timeout to avoid flakyness of some tests
  .mvn/extensions.xml
  .mvn/maven.config
  Jenkinsfile
  acceptance-tests/pom.xml
  acceptance-tests/runner/runtime/pom.xml
  acceptance-tests/runner/scripts/args.sh
  acceptance-tests/src/main/java/io/blueocean/ath/ATHJUnitRunner.java
  acceptance-tests/src/main/java/io/blueocean/ath/SmartWebElement.java
  acceptance-tests/src/main/java/io/blueocean/ath/WaitUtil.java
  acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/ActivityPage.java
  acceptance-tests/src/test/java/io/blueocean/ath/live/GithubEditorTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/FolderTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/edgeCases/TestDetailsTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/CommitMessagesTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/ParallelNavigationTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/multibranch/TestResultsErrorStdOutTest.java
  acceptance-tests/src/test/java/io/blueocean/ath/offline/personalization/FavoritesCardsTest.java
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
  pom.xml
Labels: chore

#2504 Upgrade surefire 3.1.2
  acceptance-tests/pom.xml
  acceptance-tests/runner/runtime/pom.xml
Labels: maintenance

#2503 Ignore `IOException` from `writeLogTo`
  blueocean-github-pipeline/src/test/java/io/jenkins/blueocean/blueocean_github_pipeline/GithubPipelineCreateRequestTest.java
Labels: maintenance

#2505 Prevent multiBranchPipelineIndex failure due to DirectoryNotEmptyException
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/MultiBranchTest.java
Labels: maintenance

#2508 Maven 3.9.4 for build
  Dockerfile.build
Labels: maintenance
