Repository jenkinsci/blueocean-plugin, pull requests merged in 2024-02, with the labels that each got.

#2539 chore: Add support for 'GitParameterDefinition' (Git plugin) in Blue Ocean
  blueocean-core-js/src/js/parameter/index.js
Labels: enhancement

#2532 Upgrade Jira plugin 3.12
  pom.xml
Labels: dependencies, java

#2542 Deflake `PipelineApiTest.testPipelineQueue`
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/PipelineApiTest.java
Labels: maintenance
