Repository jenkinsci/blueocean-plugin, pull requests merged in 2024-06, with the labels that each got.

#2560 Prevent debounceFetchNodes from jumping node view
  blueocean-dashboard/src/main/js/components/karaoke/components/Pipeline.jsx
Labels: bug

#2561 Prepare for coming release of git-client using Apache Mina, adapt hackhish code
  blueocean-git-pipeline/pom.xml
  blueocean-git-pipeline/src/main/java/io/jenkins/blueocean/blueocean_git_pipeline/GitUtils.java
Labels: maintenance

#2563 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: enhancement
