Repository jenkinsci/blueocean-plugin, pull requests merged in 2024-07, with the labels that each got.

#2565 Explicit dep on `matrix-project`
  blueocean-pipeline-api-impl/pom.xml
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/MatrixProjectImpl.java
  blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/analytics/MatrixAnalyticsCheck.java
Labels: bug

#2567 Simplify JSON parsing
  blueocean-rest-impl/src/main/webapp/scripts/analytics.js
Labels: internal

#2566 Fix misleading in logging statement in parallelPipeline Method
  acceptance-tests/src/main/java/io/blueocean/ath/GitRepositoryRule.java
  acceptance-tests/src/main/java/io/blueocean/ath/pages/blue/EditorPage.java
Labels: maintenance
