Repository jenkinsci/blueocean-plugin, pull requests merged in 2025-04, with the labels that each got.

#2597 Fix test for new Jenkins header
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/TryBlueOceanMenuTest.java
Labels: test

#2612 Remove Keen analytics as it is disabled and not used
  blueocean-rest-impl/pom.xml
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/analytics/KeenAnalyticsImpl.java
  blueocean-rest-impl/src/main/java/io/jenkins/blueocean/service/embedded/analytics/KeenConfiguration.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/AnalyticsTest.java
  blueocean-rest-impl/src/test/java/io/jenkins/blueocean/service/embedded/analytics/KeenAnalyticsTest.java
  pom.xml
Labels: dependencies

#2617 Prepare the blueocean-bitbucket-pipeline to the changes in bitbucket-source-branch-plugin version 936.0.1
  blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/AbstractBitbucketScm.java
  blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/AbstractBitbucketScmContentProvider.java
  blueocean-bitbucket-pipeline/src/main/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/BitbucketPipelineCreateRequest.java
  blueocean-bitbucket-pipeline/src/test/java/io/jenkins/blueocean/blueocean_bitbucket_pipeline/server/BitbucketPipelineCreateRequestTest.java
  blueocean-pipeline-api-impl/src/test/java/io/jenkins/blueocean/rest/impl/pipeline/RunImplTest.java
  pom.xml
Labels: maintenance
